### ISSUE TITLE
от сереги

### ISSUE THREAD

**Issue by whoami7o** [krpvse/dilikat_bot#1]
Привет! Серега попросил глянуть проект дать обратную связь.

По вопросам немного не по порядку пойду, чтобы какой-то смысл выстроить :/

### БД:
Выбор в сторону Связка PosterSQL + Redis - норм подход, т.к. это является довольно базовым решением и подходит для практически любого типового сервиса где нужно что-то хранить и использовать кэш, чтобы БД меньше нагружать.

Насчет того, **что можно улучшить**:

В описании написано, что тут идет работа с каталогами, скорее всего один из пользовательских сценариев - это поиск чего-то в каталоге (по названию/маркировке).
В таких случаях уместно добавление полнотекстового поиска (аля Google), т.к. SQL не предназначен для этого, т.к. синтаксис `LIKE` не вывозит такие вещи, да и сам поиск очень медленный.

Наиболее популярная технология - [ElasticSearch](https://www.elastic.co/enterprise-search/search-applications)

Обычно делаю так: основная бд (Postges/MySQL) + реплика Elastic, и все это синхронизируется бэкграунд таской какой-нибудь, которая периодически смотрит что нового в основой бд и добавляет в поисковой движок.

### Бот:

За чат ботов особо не шарю (найс ревьюер :sweat_smile:), вроде эта либа выглядит ок...
В инете только на нем примеры адекватные видел.

## 2. По архитектуре:

Общая рекомендация: обычно архитектурное решение, хотя бы на уровне сервиса, т.е. верхнеуровнего что с чем и как взаимодействует (протоколы/очереди/т.п.), принято отрисовывать в формате [диаграмм](https://miro.com/diagramming/what-is-software-architecture-diagramming/) (в идеале [UML Plant](https://plantuml.com/), но и [DrawIO](https://app.diagrams.net/) тож потянет) и класть в проект, типа в `docs/`.
Это полезно, т.к. освобождает от надобности лезть в код.

### Проектирование сервиса
В целом закинуть всю ответственность непосредственно на бота - норм, если говорить о каком-то MVP проекте, чтобы показать что идея рабочая.
Но если мы говорим о неком решении на "чистовик" и начинаем думать о больших нагрузках, то тут надо уже заниматься разделением ответственности.

1. Вынести отправку сообщений на почту в отдельный сервис-воркер (хз, например `NotificationService`), накинуть ему очередь ([RabbitMQ](https://www.rabbitmq.com/)/[Kafka](https://kafka.apache.org/)) с топиками, на которые подпишется и отправлять туда сообщения, которые он потом будет сам отправлять, а не нагружать этим бота. Этот прием оч хорош, т.к. его довольно легко масштабировать и добавлять новые виды рассылок. (там на самом деле оч много за этим решением потянется, но хотя бы минимум прикольно сделать)
2. Можно также подумать над отдельным сервисом который будет заниматься рендерингом и формированием писем/рассылок/сообщений. (но это так, на подумать)
3. Стоит даже вынести всю работу с БД в отдельный веб сервис, в который бот будет ходить с запросами. Тоже оч сильный оверкил для PetProject'а, но с точки зрения балансировки нагрузки и будущего развития приложения полезно, т.к. при выполнении п.1,2,3 бот превратиться в некий API Gateway, который по факту ничего не делает, а просто перенаправляет запросы куда надо, в чем по сути и должна заключаться его задача.

### Проектирование реализации
Не хватает [схемы БД](https://en.wikipedia.org/wiki/Database_schema) с описанием того, что там лежит и как это связано.
Также (это больше уже по реализации) нужны `ddl` скрипты и [миграции](https://alembic.sqlalchemy.org/en/latest/).
По выгрузке `.csv` файла для наполнения - норм, но лучше сделать dump бд и уже подгружать через `sql` скрипт. (там много очень приколов с `ddl` и `sql` скриптами есть для создания docker контейнера, их можно автоматически загружать)

Про `SQLAlchemy` - это база для питониста и бд, но это довольно сложный инструмент. Его преимущество в использовании его ORM либы, тут в проекте видно что ты его используешь как query билдер - прикольно, но raw-sql + asyncpg было бы проще и читаемее. Т.е. если запросов мало и они простые - лучше отказаться от алхимии.

Самое сильное, что тебя палит как начинающего - это фукциональщина и отсутсвие классов (но тут надо быть аккуратным, т.к. говно код на классах тоже палится, просто советую погрузиться в это). Это просто базовые принципы ООП, потом всякие SOLID и т.д., а потом уже упарываться во всякие паттерны.
В общем ничего криминального нет в функциональном подходе, порой где-то он полезнее, но ты довольно скоро заметишь как такой код становиться a. тяжело поддерживать b. тяжело тестировать c. невозможно дебажить d. тяжело масштабировать.

## 3. По коду
(*дико извиняюсь за духоту*)

Первое, что бросается в глаза - это [асинхронный синтаксис в синхронном коде](app/utils/validators/validators.py). Важно понимать, что под капотом делает async/await и когда он нужен.

[Валидация вручную](app/utils/validators/validators.py), конечно, прикольно, но так никто не делает, то же самое о сериализация/десериализации - все пользуются готовыми решениями, лучшее из из них - [pydantic](https://docs.pydantic.dev/latest/).

Работа с переменными окружения - круто, что использовал их, но опять же никто вручную их не парсит, то же `pydantic` их подтягивает. Также видел пару мест где гуляют какие-то константы (порты/ссылки), которые уместно было убрать туда же, а те которые не уместно принято убирать в отдельный модуль `utils/constants.py`.

Вот подробный гайд по настройке логгера - https://www.youtube.com/watch?v=9L77QExPmI0&t=651s. Сейчас принято его настраивать через `.json` или `.yaml` файл.

`app/loader.py` - эти загрузки являются частью инициализации приложения, для этого как раз в `app/main.py` существует метод `on_starup`, все загрузки должны происходить в нем. Также в методе `on_shutdown` принято "gracefully" закрывать все соединения.

тесты - отсутствие тестов и контейнера где они прогоняются - Харам. На собеседовании наверняка спросят про `functional/unit`, `integrated`, `e2e`. Стоит хотя бы по одному разу каждый из них написать, а также разобраться чекаво. Также ознакомится с моками, патчами и подобной ерундой. Тут с технологиями гораздо проще - `pytest`.

### Мелочи:

`import *` - Харам

Много `if-else` [выражений (*def change_section*)](app/handlers/main_handlers.py) - можно заменить на `dict`

`TypeHints` - сейчас в прод коде приятно прописывать типизацию всего и вся, согласно [стандарту](https://peps.python.org/pep-0484/)

`requirements.txt` - 1. надо резолвить зависимости, чтобы конфликтов не было ([poetry](https://python-poetry.org/), [pip-tools](https://pypi.org/project/pip-tools/2.0.0/)) 2. разделять их на `main` (без которых приложение нельзя запустить), `dev` (инструменты разработки, линтеры, форматеры и т.д.) и `test` (необходимые, чтобы запустить тесты)

`.env.example` - пустой файл с примерами переменных окружения, ну или с пустыми, главное чтобы можно было понять что вообще нам надо задать.

`pre-commit` - почитай про прекоммит хуки и как их настравать, вроде они ничего не делают, а код в разы лучше выглядит.

`from ..cache.catalog_cache` - относительные импорты. Многие люди тебя не поймут + они часто ломаются. Советую всегда использовать абсолютные импорты `from app.database.cache.catalog_cache`

`Dockerfile` - посмотри как их писать в несколько слоев, чтобы ускорить сборку, типа установка зависимостей в базовый образ - один слой, копирование и запуск проекта - второй слой.

Хороший проект, явно лучше, чем нынче подрядчики нам лабают. 

Советую на старте особо не обращать внимание на проектирование приложений, архитектуры, масштабируемость, хоть это сейчас от всех требуют на собесах от джунов до синьеров. А сфокусироваться просто на знании питона и навыках просто писать много кода работающего. Типа базовые задачки питониста: написать ручку в сервис, добавить проверку куда-то, написать запрос к базе, отправить/получить сообщение из очереди, покрыть новые изменения тестами. Что-то такое.

Надеюсь данная писанина окажется полезной. :-)

**Comment by krpvse** [comment]
Огромное спасибо!

Ты написал довольно много таких замечаний, к которым я сам бы в ближайшее
время точно не пришел.  Очень полезно, во всем подробно разберусь, возьму
на вооружение.


Вт, 12 марта 2024 г. в 01:43, Mikhail Petrushin ***@***.***>:

**Comment by rachet2012** [comment]
@krpvse 

Привет!

Я тоже от Сереги, замотался и совсем вылетело из головы

Довольно сложно после такого ревью от Михаила, что то добавить, но вставлю свои пять копеек:

1. По 3 пункту (>>Стоит даже вынести всю работу с БД в отдельный веб сервис)
    Для данного проекта не актуально, но думаю полезно хотя бы ознакомиться с концепциями шардирования и партицирования БД. Ну это так, чисто в ознакомительных целях
    
2. Ловить исключения следующим образом: `except Exception as e:`  - нельзя, это может создать довольно много проблем в отладке

3. Исходя из пункта 2 сразу делаем вывод -  если ожидаем каких то проблем на каком то этапе (отправка email, взаимодействие, подключение к БД), надо продумывать все такие варианты и их обработку. Например при обращение к Redis каждую операцию желательно обернуть в  `except ConnectionError as e:`.

4. Исходя из пункта 3 понимаем, что любая БД\сторонний сервис\сеть может кратковременно подвисать, что бы постараться нивелировать эти риски есть механизм `backoff`(и одноименная либа), который позволяет в случае тех же проблем с соединением попробовать повторить операцию определенное количество раз(в либе довольно гибкая настройка).

5. Так же посмотри в сторону механизма обработки таймаутов на операции с БД, сторонними сервисами. В случае большой нагрузки на них, они могут банально не успеть обработать твой запрос

6. Докстринги к функциям)


Как то так, надеюсь, что то дельное описал

**Comment by krpvse** [comment]
Привет!

Класс) Спасибо большое за дополнения, разберусь в этих моментиках тоже)

Пн, 25 марта 2024 г. в 22:49, Zakhar Bogdanov ***@***.***>:
